import './globals.css'
import 'animate.css';
import { Inter } from 'next/font/google'
import { ContextProvider, useStateContext } from '@/contexts/ContextProvider'
import { LoadingScreen } from '@/components/ui/loading/LoadingScreen';
import { MessageController } from '@/components/ui/message/MessageController';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-body">
        <ContextProvider>
          <LoadingScreen></LoadingScreen>
          <MessageController></MessageController>
          {children}
        </ContextProvider>
      </body>
    </html>
  )
}
